### ISSUE TITLE
MWT annotations?

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_English-LinES#6]
Any interest in adding MWT annotations?  For the most part, the other English treebanks such as EWT, GUM, etc all have MWTs marked on the appropriate tokens

For English, that would be

possessives such as `page's`

```
# text = When you establish a link between the connection file and a page, the page's ConnectionFile property is set to the name of the file.
```

contractions such as `don't`, `won't`:

```
# text = Siri can't do it. And I don't know how.
```

contractions of `'s` that aren't part of the more-or-less closed set of contractions:

```
# text = The glamour's off.
```

a few other random examples, such as `cannot`

```
# text = They cannot say 'I love you' so they say 'Isn't she lovely?' 'Well done.'
```

I can whip up a script and submit a PR which will do this, if this would be useful.

**Comment by LarsAhrenberg** [comment]
Thanks for messaging. So far I've not seen a need for adding MWU annotations, but I can see the point when other, larger English tree-banks have them. I tend to follow the discussions on annotation problems in EWT and GUM and think that, eventually, I'll make a larger revision when all matters have been agreed upon. If you have a script for MWU-annotations readily available I'll be happy to receive it, but otherwise I can make one myself as the items listed on the page for English tokenization seem complete.

**Comment by AngledLuffa** [comment]
I do already have such a script.  I can run it tomorrow

**Comment by AngledLuffa** [comment]
Does what I sent in for the PR look good?  Missed any?

**Comment by LarsAhrenberg** [comment]
I've just scanned a few examples. They look good.

**Comment by AngledLuffa** [comment]
Thanks, merged!
